<?php

return [
    'sections' => [
        'client_information' => [
            'label' => 'Client Information Form',
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
                ['name' => 'residence_address', 'label' => 'Residence Address', 'type' => 'text', 'required' => true],
                ['name' => 'mobile_number', 'label' => 'Mobile Number', 'type' => 'text', 'required' => true],
                ['name' => 'tin', 'label' => 'TIN', 'type' => 'text', 'required' => true],
                ['name' => 'birthdate', 'label' => 'Birthdate', 'type' => 'date', 'required' => true],
                ['name' => 'registration_date', 'label' => 'Registration Date', 'type' => 'date', 'required' => false],
                ['name' => 'alternate_contact_person', 'label' => 'Alternate Contact Person', 'type' => 'text', 'required' => false],
                ['name' => 'alternate_contact_phone_number', 'label' => 'Alternate Contact Person / Phone Number', 'type' => 'text', 'required' => false],
                ['name' => 'alternate_contact_email', 'label' => 'Alternate Contact Person / Email', 'type' => 'email', 'required' => false],
                ['name' => 'product_industry_1', 'label' => 'Product / Industry 1', 'type' => 'text', 'required' => false],
                ['name' => 'product_industry_2', 'label' => 'Product / Industry 2', 'type' => 'text', 'required' => false],
            ],
        ],
        'treasurer_details' => [
            'label' => 'Treasurer Details',
            'fields' => [
                ['name' => 'corporate_name', 'label' => 'Corporate Name', 'type' => 'text', 'required' => false],
                ['name' => 'treasurer_first_name', 'label' => 'Treasurer First Name', 'type' => 'text', 'required' => false],
                ['name' => 'treasurer_middle_name', 'label' => 'Treasurer Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'treasurer_surname', 'label' => 'Treasurer Surname', 'type' => 'text', 'required' => false],
                ['name' => 'treasurer_address', 'label' => 'Treasurer Address', 'type' => 'text', 'required' => false],
                ['name' => 'treasurer_mobile_number', 'label' => 'Treasurer Mobile Number', 'type' => 'text', 'required' => false],
                ['name' => 'treasurer_birthdate', 'label' => 'Treasurer Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'treasurer_tin', 'label' => 'Treasurer Tax Identification Number', 'type' => 'text', 'required' => false],
                ['name' => 'assistant_treasurer_first_name', 'label' => 'Assistant Treasurer First Name', 'type' => 'text', 'required' => false],
                ['name' => 'assistant_treasurer_middle_name', 'label' => 'Assistant Treasurer Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'assistant_treasurer_surname', 'label' => 'Assistant Treasurer Surname', 'type' => 'text', 'required' => false],
                ['name' => 'assistant_treasurer_address', 'label' => 'Assistant Treasurer Address', 'type' => 'text', 'required' => false],
                ['name' => 'assistant_treasurer_mobile_number', 'label' => 'Assistant Treasurer Mobile Number', 'type' => 'text', 'required' => false],
                ['name' => 'assistant_treasurer_birthdate', 'label' => 'Assistant Treasurer Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'assistant_treasurer_tin', 'label' => 'Assistant Treasurer Tax Identification Number', 'type' => 'text', 'required' => false],
            ],
        ],
        'opc_details' => [
            'label' => 'OPC Details',
            'fields' => [
                ['name' => 'proposed_corporation_name_1', 'label' => 'Proposed Corporation Name 1', 'type' => 'text', 'required' => true],
                ['name' => 'proposed_corporation_name_2', 'label' => 'Proposed Corporation Name 2', 'type' => 'text', 'required' => false],
                ['name' => 'proposed_corporation_name_3', 'label' => 'Proposed Corporation Name 3', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_first_name', 'label' => 'Incorporator First Name', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_middle_name', 'label' => 'Incorporator Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_surname', 'label' => 'Incorporator Surname', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_birthdate', 'label' => 'Incorporator Birthdate', 'type' => 'date', 'required' => true],
                ['name' => 'incorporator_complete_address', 'label' => 'Incorporator Complete Address', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_tin', 'label' => 'Incorporator Tax Identification Number', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_email_address', 'label' => 'Incorporator E-Mail Address', 'type' => 'email', 'required' => true],
                ['name' => 'incorporator_contact_number', 'label' => 'Incorporator Contact Number', 'type' => 'text', 'required' => true],
                ['name' => 'nominee_first_name', 'label' => 'Nominee First Name', 'type' => 'text', 'required' => true],
                ['name' => 'nominee_middle_name', 'label' => 'Nominee Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'nominee_surname', 'label' => 'Nominee Surname', 'type' => 'text', 'required' => true],
                ['name' => 'nominee_birthdate', 'label' => 'Nominee Birthdate', 'type' => 'date', 'required' => true],
                ['name' => 'nominee_complete_address', 'label' => 'Nominee Complete Address', 'type' => 'text', 'required' => true],
                ['name' => 'nominee_tin', 'label' => 'Nominee Tax Identification Number', 'type' => 'text', 'required' => true],
                ['name' => 'nominee_email_address', 'label' => 'Nominee E-Mail Address', 'type' => 'email', 'required' => true],
                ['name' => 'nominee_contact_number', 'label' => 'Nominee Contact Number', 'type' => 'text', 'required' => true],
                ['name' => 'alternate_nominee_first_name', 'label' => 'Alternate Nominee First Name', 'type' => 'text', 'required' => true],
                ['name' => 'alternate_nominee_middle_name', 'label' => 'Alternate Nominee Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'alternate_nominee_surname', 'label' => 'Alternate Nominee Surname', 'type' => 'text', 'required' => true],
                ['name' => 'alternate_nominee_birthdate', 'label' => 'Alternate Nominee Birthdate', 'type' => 'date', 'required' => true],
                ['name' => 'alternate_nominee_complete_address', 'label' => 'Alternate Nominee Complete Address', 'type' => 'text', 'required' => true],
                ['name' => 'alternate_nominee_tin', 'label' => 'Alternate Nominee Tax Identification Number', 'type' => 'text', 'required' => true],
                ['name' => 'alternate_nominee_email_address', 'label' => 'Alternate Nominee E-Mail Address', 'type' => 'email', 'required' => true],
                ['name' => 'alternate_nominee_contact_number', 'label' => 'Alternate Nominee Contact Number', 'type' => 'text', 'required' => true],
            ],
        ],
        'proprietorship' => [
            'label' => 'Proprietorship Details',
            'fields' => [
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true],
                ['name' => 'address', 'label' => 'Address', 'type' => 'text', 'required' => true],
                ['name' => 'proposed_business_name_1', 'label' => 'Proposed Business Name 1', 'type' => 'text', 'required' => true],
                ['name' => 'proposed_business_name_2', 'label' => 'Proposed Business Name 2', 'type' => 'text', 'required' => false],
                ['name' => 'business_address', 'label' => 'Business Address', 'type' => 'text', 'required' => true],
                ['name' => 'mobile_number', 'label' => 'Mobile Number', 'type' => 'text', 'required' => true],
                ['name' => 'organization_type', 'label' => 'Organization Type (Sole Prop, Corp, Others)', 'type' => 'text', 'required' => false],
                ['name' => 'tin', 'label' => 'TIN', 'type' => 'text', 'required' => true],
                ['name' => 'tax_type', 'label' => 'Tax Type (VAT/NON VAT)', 'type' => 'text', 'required' => true],
                ['name' => 'birthdate', 'label' => 'Birthdate', 'type' => 'date', 'required' => true],
                ['name' => 'mother_maiden_name', 'label' => 'Mother\'s Maiden Name', 'type' => 'text', 'required' => false],
                ['name' => 'mother_birthdate', 'label' => 'Mother\'s Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'father_name', 'label' => 'Father\'s Name', 'type' => 'text', 'required' => false],
                ['name' => 'father_birthdate', 'label' => 'Father\'s Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'spouse_name', 'label' => 'Spouse\'s Name', 'type' => 'text', 'required' => false],
                ['name' => 'spouse_birthdate', 'label' => 'Spouse\'s Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'registration_date', 'label' => 'Registration Date', 'type' => 'date', 'required' => false],
                ['name' => 'alternate_contact_person', 'label' => 'Alternate Contact Person', 'type' => 'text', 'required' => false],
                ['name' => 'alternate_contact_phone_number', 'label' => 'Alternate Contact Person / Phone Number', 'type' => 'text', 'required' => false],
                ['name' => 'alternate_contact_email', 'label' => 'Alternate Contact Person / Email', 'type' => 'email', 'required' => false],
                ['name' => 'product_industry_1', 'label' => 'Product / Industry 1', 'type' => 'text', 'required' => false],
                ['name' => 'product_industry_2', 'label' => 'Product / Industry 2', 'type' => 'text', 'required' => false],
            ],
        ],
        'regular_corporation' => [
            'label' => 'Regular Corporation Details',
            'fields' => [
                ['name' => 'proposed_corporation_name_1', 'label' => 'Proposed Corporation Name 1', 'type' => 'text', 'required' => true],
                ['name' => 'proposed_corporation_name_2', 'label' => 'Proposed Corporation Name 2', 'type' => 'text', 'required' => false],
                ['name' => 'proposed_corporation_name_3', 'label' => 'Proposed Corporation Name 3', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_1_first_name', 'label' => 'Incorporator 1 First Name', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_1_middle_name', 'label' => 'Incorporator 1 Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_1_surname', 'label' => 'Incorporator 1 Surname', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_1_birthdate', 'label' => 'Incorporator 1 Birthdate', 'type' => 'date', 'required' => true],
                ['name' => 'incorporator_1_complete_address', 'label' => 'Incorporator 1 Complete Address', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_1_tin', 'label' => 'Incorporator 1 Tax Identification Number', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_1_email_address', 'label' => 'Incorporator 1 E-Mail Address', 'type' => 'email', 'required' => true],
                ['name' => 'incorporator_1_contact_number', 'label' => 'Incorporator 1 Contact Number', 'type' => 'text', 'required' => true],
                ['name' => 'incorporator_2_first_name', 'label' => 'Incorporator 2 First Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_2_middle_name', 'label' => 'Incorporator 2 Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_2_surname', 'label' => 'Incorporator 2 Surname', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_2_birthdate', 'label' => 'Incorporator 2 Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'incorporator_2_complete_address', 'label' => 'Incorporator 2 Complete Address', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_2_tin', 'label' => 'Incorporator 2 Tax Identification Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_2_email_address', 'label' => 'Incorporator 2 E-Mail Address', 'type' => 'email', 'required' => false],
                ['name' => 'incorporator_2_contact_number', 'label' => 'Incorporator 2 Contact Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_3_first_name', 'label' => 'Incorporator 3 First Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_3_middle_name', 'label' => 'Incorporator 3 Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_3_surname', 'label' => 'Incorporator 3 Surname', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_3_birthdate', 'label' => 'Incorporator 3 Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'incorporator_3_complete_address', 'label' => 'Incorporator 3 Complete Address', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_3_tin', 'label' => 'Incorporator 3 Tax Identification Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_3_email_address', 'label' => 'Incorporator 3 E-Mail Address', 'type' => 'email', 'required' => false],
                ['name' => 'incorporator_3_contact_number', 'label' => 'Incorporator 3 Contact Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_4_first_name', 'label' => 'Incorporator 4 First Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_4_middle_name', 'label' => 'Incorporator 4 Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_4_surname', 'label' => 'Incorporator 4 Surname', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_4_birthdate', 'label' => 'Incorporator 4 Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'incorporator_4_complete_address', 'label' => 'Incorporator 4 Complete Address', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_4_tin', 'label' => 'Incorporator 4 Tax Identification Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_4_email_address', 'label' => 'Incorporator 4 E-Mail Address', 'type' => 'email', 'required' => false],
                ['name' => 'incorporator_4_contact_number', 'label' => 'Incorporator 4 Contact Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_5_first_name', 'label' => 'Incorporator 5 First Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_5_middle_name', 'label' => 'Incorporator 5 Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_5_surname', 'label' => 'Incorporator 5 Surname', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_5_birthdate', 'label' => 'Incorporator 5 Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'incorporator_5_complete_address', 'label' => 'Incorporator 5 Complete Address', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_5_tin', 'label' => 'Incorporator 5 Tax Identification Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_5_email_address', 'label' => 'Incorporator 5 E-Mail Address', 'type' => 'email', 'required' => false],
                ['name' => 'incorporator_5_contact_number', 'label' => 'Incorporator 5 Contact Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_6_first_name', 'label' => 'Incorporator 6 First Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_6_middle_name', 'label' => 'Incorporator 6 Middle Name', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_6_surname', 'label' => 'Incorporator 6 Surname', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_6_birthdate', 'label' => 'Incorporator 6 Birthdate', 'type' => 'date', 'required' => false],
                ['name' => 'incorporator_6_complete_address', 'label' => 'Incorporator 6 Complete Address', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_6_tin', 'label' => 'Incorporator 6 Tax Identification Number', 'type' => 'text', 'required' => false],
                ['name' => 'incorporator_6_email_address', 'label' => 'Incorporator 6 E-Mail Address', 'type' => 'email', 'required' => false],
                ['name' => 'incorporator_6_contact_number', 'label' => 'Incorporator 6 Contact Number', 'type' => 'text', 'required' => false],
            ],
        ],
    ],
    'company_type_sections' => [
        'opc' => 'opc_details',
        'sole_prop' => 'proprietorship',
        'corp' => 'regular_corporation',
    ],
];
